### ISSUE TITLE
Resources View

### ISSUE THREAD

**Issue by metalost** [Smoxer/Ika#7]
![image](https://user-images.githubusercontent.com/31975628/34322532-9b17921c-e7ff-11e7-9ee8-ddda82a8535f.png)

I would like an eyelash to see the resources of my cities like that, that shows in another tab the buildings or the construction queues that are in progress (Or if there is or there is not)

Thank you very much for your attention

**Comment by Smoxer** [comment]
This is an issue report, not a suggestion page.
